//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.13 at 02:43:48 PM MSK 
//


package ru.malichenko.market.ws.orders;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="allOrders" type="{http://www.malichenko.ru/market/ws/orders}orders" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "allOrders"
})
@XmlRootElement(name = "getOrdersByUserResponse")
public class GetOrdersByUserResponse {

    @XmlElement(required = true)
    protected List<Orders> allOrders;

    public void setAllOrders(List<Orders> allOrders) {
        this.allOrders = allOrders;
    }

    /**
     * Gets the value of the allOrders property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allOrders property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllOrders().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Orders }
     */
    public List<Orders> getAllOrders() {
        if (allOrders == null) {
            allOrders = new ArrayList<Orders>();
        }
        return this.allOrders;
    }

}
