//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.13 at 02:43:48 PM MSK 
//


package ru.malichenko.market.ws.orders;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.malichenko.market.ws.orders package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.malichenko.market.ws.orders
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetOrdersByUserRequest }
     * 
     */
    public GetOrdersByUserRequest createGetOrdersByUserRequest() {
        return new GetOrdersByUserRequest();
    }

    /**
     * Create an instance of {@link GetOrdersByUserResponse }
     * 
     */
    public GetOrdersByUserResponse createGetOrdersByUserResponse() {
        return new GetOrdersByUserResponse();
    }

    /**
     * Create an instance of {@link Orders }
     * 
     */
    public Orders createOrders() {
        return new Orders();
    }

    /**
     * Create an instance of {@link OrderItem }
     * 
     */
    public OrderItem createOrderItem() {
        return new OrderItem();
    }

}
